In [1]:
import numpy as np
import math

In [3]:
ru = [chr(i) for i in range (ord('а'), ord('я') + 1)]
en = [chr(i) for i in range (ord('a'), ord('z') + 1)]

In [7]:
text = 'Здравствуйте, я Григорий'
newText = text.replace(' ', '').lower()
key = 'пароль'
keyLetters = {key[i] : i for i in range (len(key))}
keyLen = len(key)
textLen = len(newText)
m = int(round(textLen/keyLen))
A = np.full((m,keyLen), '')

for i in range(m*keyLen - textLen):
    newText += newText[-1]

tmp_count = 0
for i in range(m):
    for j in range(keyLen):
        A[i][j] = newText[tmp_count]
        tmp_count += 1
        
print(keyLen, m)
print(np.matrix(A))

6 4
[['з' 'д' 'р' 'а' 'в' 'с']
 ['т' 'в' 'у' 'й' 'т' 'е']
 [',' 'я' 'г' 'р' 'и' 'г']
 ['о' 'р' 'и' 'й' 'й' 'й']]


### Номер 2

In [34]:
text = 'Здравствуйте я Григорий'
newText = text.replace(' ', '').lower()
textLen = len(newText)
size = np.ceil(np.sqrt(textLen)) # Количество числе в маленькой таблице

while size % np.sqrt(size) != 0:
    size += 1
size = int(size)

i = 0
while i < (size ** 2 - textLen):
    newText += '*'
    i += 1
    
tableSize = int(np.sqrt(size)) # Размер маленькой таблциы
quaterTable = np.arange(1,size+1) # Массив с числами маленькой таблицы
print(newText, size, tableSize, quaterTable)

здравствуйтеягригорий************************************************************ 9 3 [1 2 3 4 5 6 7 8 9]


In [14]:
def rotate(A): # Поворот вправо на 90 градусов
    result = np.empty(shape=(A.shape[1],A.shape[0]))
    for i in range (A.shape[0]):
        for j in range (A.shape[1]):
            result[j, A.shape[0]-i-1] = A[i,j]
    return result

In [36]:
A0 = np.empty((tableSize, tableSize))
for k in range(size):
    n = 0
    for i in range(tableSize):
        for j in range(tableSize):
            A0[i][j] = quaterTable[n]
            n += 1
A1 = np.concatenate((A0, rotate(A0)), axis=1)
A2 = np.concatenate((A1, rotate(rotate(A1))), axis=0)

B = np.zeros((tableSize*2, tableSize*2))

_tmp = quaterTable.copy()
for k in range (size):
    randCount = np.random.randint(4)
    tmp_count = 0
    for i in range (tableSize*2):
        for j in range (tableSize*2):
            if (A2[i][j] == k + 1):
                if(tmp_count == randCount):
                    B[i][j] = A2[i][j]
                    tmp_count = -1000000
                    _tmp = _tmp[_tmp != k+1]
                else:
                    tmp_count += 1
print(B)

[[0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 8. 5. 0.]
 [0. 0. 0. 9. 6. 0.]
 [0. 0. 0. 0. 0. 7.]
 [0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 3. 0. 1.]]


In [40]:
fillness = 0
answer = [[''] * tableSize*2 for i in range(tableSize*2)]

for abc in range(4):
    for i in range (tableSize*2):
        for j in range (tableSize*2):
            if(B[i][j] != 0):
                answer[i][j] = newText[fillness]
                fillness += 1
    B = rotate(B)
    
print(np.matrix(answer))

[['р' 'з' 'и' '*' 'й' '*']
 ['й' '*' '*' 'д' 'р' 'т']
 ['*' '*' '*' 'а' 'в' '*']
 ['е' '*' '*' 'я' 'г' 'с']
 ['*' '*' '*' 'р' 'и' '*']
 ['г' 'т' 'о' 'в' '*' 'у']]


In [42]:
tmp_key = ''

while(len(tmp_key) != tableSize*2):
    tmp_rand = np.random.randint(len(ru))
    if(tmp_key.count(ru[tmp_rand]) == 0):
        tmp_key += ru[tmp_rand]
        
key = tmp_key
print(key)

лаиэьй


In [45]:
minimum = 999999999
ans_text = ''
min_index = 0
for i in range(len(key)):
    for j in range(len(tmp_key)):
        if(ord(tmp_key[j]) < minimum):
            minimum = ord(tmp_key[j])
            min_index = j
    for j in range(tableSize*2):
        ans_text += answer[j][min_index]
    tmp_key = tmp_key.replace(tmp_key[min_index], chr(ord('я')+3))
    minimum = 999999

In [46]:
print('Ваш текст : ', text)
print('Matrix B:\n', np.matrix(B))
print('Result matrix\n', np.matrix(answer))
print('Key = ', key)
print('Cyphered text = ', ans_text)

Ваш текст :  Здравствуйте я Григорий
Matrix B:
 [[0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 8. 5. 0.]
 [0. 0. 0. 9. 6. 0.]
 [0. 0. 0. 0. 0. 7.]
 [0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 3. 0. 1.]]
Result matrix
 [['р' 'з' 'и' '*' 'й' '*']
 ['й' '*' '*' 'д' 'р' 'т']
 ['*' '*' '*' 'а' 'в' '*']
 ['е' '*' '*' 'я' 'г' 'с']
 ['*' '*' '*' 'р' 'и' '*']
 ['г' 'т' 'о' 'в' '*' 'у']]
Key =  лаиэьй
Cyphered text =  з****ти****о*т*с*урй*е*гйрвги**даярв


### Номер 3

In [47]:
letters = {ru[i] : i for i in range(len(ru))}

In [51]:
vignere_table = np.array(ru)
for i in range(1, len(ru)):
    row = np.roll(ru,-i)
    vignere_table = np.vstack((vignere_table,row))

In [52]:
text = 'Здравствуйте я Григорий'
newText = text.replace(' ', '').lower()
key = 'Карта'
newKey = key.lower()

keyLen = len(newKey)
textLen = len(newText)
_key = newKey

while len(_key) < textLen:
    k = len(_key)
    _key += _key[k-n]

result = ""
for i in range(textLen):
    x = letters[_key[i]]
    y = letters[newText[i]]
    result += vignere_table[x][y]

print(result)

сдатвсдвуутхсгръгоъищ
